apiVersion: v1
kind: Service
metadata:
  name: master-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 6006
  selector:
    app: tensorboard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard
  namespace: default
  labels:
    app: tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard
  template:
    metadata:
      name: tensorboard
      namespace: default
      labels:
        app: tensorboard
    spec:
      containers:
      - name: tensorboard
        image: tensorflow/tensorflow:2.3.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install tensorboard
            tensorboard --logdir /log --bind_all
        ports:
          - containerPort: 6006
