apiVersion: v1
kind: Service
metadata:
  name: master-svc
  namespace: distrl
spec:
  ports:
  - port: 80
    targetPort: 6006
  selector:
    type: tf-board

---
apiVersion: v1
kind: Pod
metadata:
  name: master
  namespace: dsitrl
  labels:
    type: master
spec:
  containers:
    name: tfboard
    image:
