apiVersion: v1
kind: Pod
metadata:
  name: learner-pod
  namespace: default
  labels:
    app: learner
spec:
  containers:
  - name: ray-gpu-actor
    image: gcr.io/distrl-project/distrl
    command: ["/bin/sh", "-c"]
    args:
      - |
        ray start --address='ray-headless-svc:6379'
        while true
        do
          sleep 5
        done
    resources:
      requests:
        cpu: "8"

---
apiVersion: v1
kind: Pod
metadata:
  name: actor-pod
  namespace: default
  labels:
    app: actor
spec:
  containers:
  - name: ray-cpu-actor
    image: gcr.io/distrl-project/distrl
    command: ["/bin/sh", "-c"]
    args:
      - |
        ray start --address='ray-headless-svc:6379'
        while true
        do
          sleep 5
        done
    resources:
      requests:
        cpu: "8"

---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
  labels:
    app: debug
spec:
  containers:
    - name: debug
      image: centos:7
      command: ["sh", "-c"]
      args:
        - |
          yum install bind-utils -y
          while true
          do
            sleep 5
          done
